In [ ]:
#head file
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , f1_score , recall_score , precision_score , classification_report
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# read path of a file
df = pd.read_csv("C:\\Users\\ayush\\OneDrive\\Documents\\credit_card_file.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
# count number of null in evey column
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# countplot of class type 
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
# this data is unbalanced data 
legit = df[df['Class'] == 0]
fraud = df[df['Class'] == 1]

In [ ]:
legit.shape
fraud.shape

(492, 31)

In [ ]:
legit = legit.sample(n = 492)
df_updated = pd.concat([legit , fraud] , axis = 0)

In [ ]:
print(df_updated)

            Time        V1        V2        V3        V4        V5        V6  \
15360    26748.0  1.625070 -0.984300 -0.143234 -1.652617 -0.878569 -0.228601
27489    34570.0  1.411564 -1.232946  0.801654 -1.282521 -1.943910 -0.830439
88905    62344.0 -0.937574  0.375183  0.857361 -1.946554 -0.740464 -0.550526
203491  134842.0  1.982849 -0.433256 -1.165862  0.544396 -0.182160 -0.385039
31578    36421.0  0.933799 -1.487429  0.788898 -0.583519 -1.430697  0.543424
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V21       V22       V23  \
15360  -0.956258 -0.149410 -1.723440  ... -0.310629 -0.493630 -0.132593
27489  -1.210123 -0.103866 -1.520176  ... -0.260823 -0.510538  0.113410
88905   0.125472  0.340648 -1.668178  ...  0.434858  0.903209 -0.257751
203491 -0.221167  0.028392  0.918710  ...  0.089151  0.414630  0.022104
31578  -1.114958  0.287432 -0.303724  ...  0.474056  1.001207 -0.286532
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173

             V24       V25       V26       V27       V28  Amount  Class
15360  -1.032121  0.569951 -0.119009  0.027641  0.005893   10.00      0
27489   0.321600  0.106883 -0.334594  0.039047  0.037220   55.00      0
88905   0.019118  0.124857 -0.293578 -0.146358  0.005870   72.60      0
203491 -0.380506  0.057750  0.467845 -0.063246 -0.080717   16.92      0
31578  -0.243804  0.316955 -0.032866  0.024488  0.040446  196.58      0
...          ...       ...       ...       ...       ...     ...    ...
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1

[984 rows x 31 columns]

In [ ]:
df_updated.shape
df_updated['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [ ]:
x = df_updated.drop(columns= 'Class' , axis= 1)
y = df_updated['Class']

In [ ]:
##train test split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.3 , random_state=42)

In [ ]:
##Logistic Regression

lg_model = LogisticRegression()
lg_model.fit(x_train , y_train)

# training on prediction
x_train_pred = lg_model.predict(x_train)

print("training data results : \n")

print("accuracy : " , accuracy_score(x_train_pred , y_train))
print("f1 score : " , f1_score(x_train_pred , y_train))
print("recall score : " , recall_score(x_train_pred , y_train))
print("precision_score : " , precision_score(x_train_pred , y_train))
print(classification_report(x_train_pred , y_train))

# training on test
print("\ntesting data results : ")
x_test_pred = lg_model.predict(x_test)
print("accuracy : " , accuracy_score(x_test_pred , y_test))
print("f1 score : " , f1_score(x_test_pred , y_test))
print("recall score : " , recall_score(x_test_pred , y_test))
print("precision_score : " , precision_score(x_test_pred , y_test))
print(classification_report(x_test_pred , y_test))

training data results :

accuracy :  0.9433139534883721
f1 score :  0.9420505200594353
recall score :  0.9694189602446484
precision_score :  0.9161849710982659
              precision    recall  f1-score   support

           0       0.97      0.92      0.94       361
           1       0.92      0.97      0.94       327

    accuracy                           0.94       688
   macro avg       0.94      0.94      0.94       688
weighted avg       0.94      0.94      0.94       688


testing data results :
accuracy :  0.9358108108108109
f1 score :  0.9328621908127208
recall score :  0.9635036496350365
precision_score :  0.9041095890410958
              precision    recall  f1-score   support

           0       0.97      0.91      0.94       159
           1       0.90      0.96      0.93       137

    accuracy                           0.94       296
   macro avg       0.94      0.94      0.94       296
weighted avg       0.94      0.94      0.94       296

c:\Users\ayush\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
##Decision Tree Classifier
# Training data results
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
print("Decision Tree - Training data results:\n")
x_train_pred = dt_model.predict(x_train)
print("Accuracy:", accuracy_score(x_train_pred, y_train))
print("F1 Score:", f1_score(x_train_pred, y_train))
print("Recall Score:", recall_score(x_train_pred, y_train))
print("Precision Score:", precision_score(x_train_pred, y_train))
print(classification_report(x_train_pred, y_train))

# Testing data results
print("\nDecision Tree - Testing data results:\n")
x_test_pred = dt_model.predict(x_test)
print("Accuracy:", accuracy_score(x_test_pred, y_test))
print("F1 Score:", f1_score(x_test_pred, y_test))
print("Recall Score:", recall_score(x_test_pred, y_test))
print("Precision Score:", precision_score(x_test_pred, y_test))
print(classification_report(x_test_pred, y_test))

Decision Tree - Training data results:

Accuracy: 1.0
F1 Score: 1.0
Recall Score: 1.0
Precision Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       342
           1       1.00      1.00      1.00       346

    accuracy                           1.00       688
   macro avg       1.00      1.00      1.00       688
weighted avg       1.00      1.00      1.00       688


Decision Tree - Testing data results:

Accuracy: 0.9054054054054054
F1 Score: 0.903448275862069
Recall Score: 0.9097222222222222
Precision Score: 0.8972602739726028
              precision    recall  f1-score   support

           0       0.91      0.90      0.91       152
           1       0.90      0.91      0.90       144

    accuracy                           0.91       296
   macro avg       0.91      0.91      0.91       296
weighted avg       0.91      0.91      0.91       296

In [ ]:
# Random Forest Classifier

rf_model = RandomForestClassifier()
rf_model.fit(x_train, y_train)

# Training data results
print("Random Forest - Training data results:\n")
x_train_pred = rf_model.predict(x_train)
print("Accuracy:", accuracy_score(x_train_pred, y_train))
print("F1 Score:", f1_score(x_train_pred, y_train))
print("Recall Score:", recall_score(x_train_pred, y_train))
print("Precision Score:", precision_score(x_train_pred, y_train))
print(classification_report(x_train_pred, y_train))

# Testing data results
print("\nRandom Forest - Testing data results:\n")
x_test_pred = rf_model.predict(x_test)
print("Accuracy:", accuracy_score(x_test_pred, y_test))
print("F1 Score:", f1_score(x_test_pred, y_test))
print("Recall Score:", recall_score(x_test_pred, y_test))
print("Precision Score:", precision_score(x_test_pred, y_test))
print(classification_report(x_test_pred, y_test))

Random Forest - Training data results:

Accuracy: 1.0
F1 Score: 1.0
Recall Score: 1.0
Precision Score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       342
           1       1.00      1.00      1.00       346

    accuracy                           1.00       688
   macro avg       1.00      1.00      1.00       688
weighted avg       1.00      1.00      1.00       688


Random Forest - Testing data results:

Accuracy: 0.9391891891891891
F1 Score: 0.9361702127659575
Recall Score: 0.9705882352941176
Precision Score: 0.9041095890410958
              precision    recall  f1-score   support

           0       0.97      0.91      0.94       160
           1       0.90      0.97      0.94       136

    accuracy                           0.94       296
   macro avg       0.94      0.94      0.94       296
weighted avg       0.94      0.94      0.94       296

CREATING USER INPUT INTERFACE

In [ ]:
data = {7526	,0.008430365	,4.137836835,	-6.240696572,	6.675732163,	0.768307025,	-3.353059548,	-1.631734673,	0.154612448	,-2.795892464,	-6.18789063	,5.664394709,	-9.854484823	,-0.306166658,	-10.69119621,	-0.638498193,	-2.041973791,	-1.129055877,	0.116452521,	-1.934665739,	0.488378221	,0.36451421	,-0.608057134	,-0.539527942	,0.128939983	,1.48848121	,0.507962678	,0.735821636	,0.513573741	,1	
}
data=pd.DataFrame(data).T

In [ ]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.768307,-0.306167,0.154612,-0.638498,4.137837,5.664395,6.675732,0.488378,0.364514,-0.608057,...,-1.934666,0.116453,0.507963,-10.691196,-9.854485,0.513574,-6.187891,-3.35306,-2.041974,-1.129056

In [ ]:
y=rf_model.predict(data)
if y[0] ==1:
    print("Fraud")
else:
    print("Legit")

Fraud

c:\Users\ayush\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(